apiVersion: ops.example.com/v1alpha1
kind: SecretSync
metadata:
  labels:
    app.kubernetes.io/name: secret-sync-operator
    app.kubernetes.io/managed-by: kustomize
  name: secretsync-sample
spec:
  # TODO(user): Add fields here
  provider:
    type: aws
    key: my-provider
  remote:
    name: production/database
  target:
    name: database-secret
