apiVersion: ops.example.com/v1alpha1
kind: SecretSync
metadata:
  labels:
    app.kubernetes.io/name: secret-sync-operator
    app.kubernetes.io/managed-by: kustomize
  name: secretsync-sample
spec:
  refreshInterval: 10m
  provider:
    type: aws
  remote:
    name: production/database
  target:
    name: database-secret
